# Generated by Django 4.2.7 on 2024-03-28 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="products",
        ),
    ]
