# Generated by Django 4.2.7 on 2024-03-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_product_image"),
        ("carts", "0002_remove_cart_products"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="products",
            field=models.ManyToManyField(
                through="carts.CartProducts", to="products.product"
            ),
        ),
    ]
