# Generated by Django 4.2.7 on 2023-12-13 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_slug_alter_product_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(default="", upload_to="products/"),
            preserve_default=False,
        ),
    ]
